#!/usr/bin/env bash

set_output() {
  output="$1"
  width="$2"
  height="$3"
  rate="${4:-60}"
  position="${5:-0x0}"
  modeline="$(cvt "$width" "$height" "$rate" | tail -n +2 | awk '{$1=""; print substr($0,2)}')"
  # shellcheck disable=SC2116,SC2046
  xrandr --newmode $(echo "$modeline")
  modename="$(echo "$modeline" | awk '{print $1}')"
  xrandr --addmode "$output" "$modename"
  xrandr --output "$output" --mode "$modename" --pos "$position"
}
# change me or add more outputs
# set_output 'output name' 'w h r'
# find outputs with xrandr -q

set_output Virtual-1 3840 2160
