#!/bin/sh

set_output() {
  output="$1"
  resolution="$2"
  position="${3:-0x0}"
  modeline="$(cvt "$resolution" | tail -n +2 | awk '{$1=""; print $0}')"
  modename="$(echo "$modeline" | awk '{print $1}')"
  xrandr --newmode "$modeline"
  xrandr --addmode "$output" --mode "$modename"
  xrandr --output "$output" --mode "$modename" --pos "$position"
}
# change me or add more outputs
# set_output 'output name' 'w h r'
# find outputs with xrandr -q

set_output 'Virtual-1' '3840 2160 60'
